### ISSUE TITLE
Insert installation instructions and info

### ISSUE THREAD

**Issue by meditans** [d12frosted/environment#1] opened 2015-10-05 14:05 UTC
Hi, it would be nice to detail in your Readme what this layer can and cannot do: I don't mean how to install the layer, but what options are configurable, and, for example, how to get this layer working with ghc-mod.

Another nice add-on would be to explain how this layer differs from the haskell layer spacemacs already has.

Moreover, if you have tips on how to get a working installation of stack+spacemacs+ghc-mod, feel free to tell me :)

**Comment by d12frosted** [comment] 2015-10-05 14:26
You are referring to `d12-haskell` layer, right?

When there were some problems with `stack` + `ghc-mod` my layer wasn't using `ghc-mod` at all, but rather `company-cabal` (or something like this). After `ghc-mod` befriended with `stack` I reverted to default `haskell` layer, but since it has pretty bad configurations for `structured-haskell-mode` (it breaks default behaviour), I cloned that `haskell` layer and just changed configurations to `structured-haskell-mode`. 

So basically, at the time being I wouldn't recommend using this layer. Default one is very nice and I recommend you to use it. :smile: 

As for `structured-haskell-mode`... Well, if you are using `emacs` editing style - then I recommend you to disable `shm` support in default `haskell` layer and adding `structured-haskell-mode` as additional package. It has very nice configurations for emacs users. But since I don't use evil - unfortunately, I can't help you with setting up `structured-haskell-mode` for it in a way that it works as intended. 

---

As for installing all required tools. It's till a bit complicated, but just yesterday I fresh installed everything and this how I did:

1. Install emacs / spacemacs.
2. Install `stack` [v0.1.5.0](https://github.com/commercialhaskell/stack/releases/tag/v0.1.5.0).
3. Use `lts-3.7` resolver in `stack.yaml` [global](https://github.com/d12frosted/environment/blob/master/haskell/stack-global.yaml).
4. Call `stack setup`.
5. Install some packages using `stack`: `stack install hlint structured-haskell-mode stylish-haskell`.
6. Clone `ghc-mod` from [official repository](https://github.com/kazu-yamamoto/ghc-mod).
7. Edit `stack.yaml` in local copy of `ghc-mod` repository (read further to see how it should look after edit).
8. Call `stack install`. Now `ghc-mod` should be installed and you should be happy. If not - feel free to ask me for help!

---

**Content of `stack.yaml` in `ghc-mod`**

```
flags: {}
packages:
- '.'
- location:
    git: git@github.com:DanielG/cabal-helper.git
    commit: c2f6a2e5bf40f9e4cb9276bcc9b58ec3627f727a
extra-deps:
- cabal-helper-0.6.0.0
resolver: lts-3.1
```

---

Hope it helps.

**Comment by meditans** [comment] 2015-10-05 15:21
Thanks for the quick reply :) I installed all like you said (only using `lts-3.8` as my global resolver - by the way, is it important to have `lts-3.1`, instead of `lts-3.8`, in the `ghc-mod` `stack.yaml`?)

I also added to my `PATH` the actual location of the `ghc` binary (otherwise `ghc-mod` complains) and `~/.local/bin`.

I activated the layer with:

    (haskell
      :variables
      haskell-enable-ghc-mod-support t
      haskell-enable-ghci-ng-support t
    )

But I'm still unable to get type info from `ghc-mod` (`C-c C-t` or the extended command). It just says `Cannot determine type`. And I cannot case split or do anything else.
Do you have any suggestion?

**Comment by d12frosted** [comment] 2015-10-05 15:52
> `lts-3.8`

Oh, it's already out. Fast. But I think it doesn't matter in this case :smile: 

> by the way, is it important to have lts-3.1, instead of lts-3.8, in the ghc-mod stack.yaml?

I haven't changed that. I think you should leave it as is. But in case of any problems - `stack` will find another resolver anyway, so don't bother yourself with reinstalling if you already installed with other resolver. 

> I also added to my PATH the actual location of the ghc binary

Ah, right. Forgot to tell you this. Sorry :smile: 

> `haskell-enable-ghci-ng-support t`

Have you installed `ghci-ng`? 

> And I cannot case split or do anything else.

I thought that it's `structured-haskell-mode` functionality.

> But I'm still unable to get type info

Make sure that you call it not on the function type definition. What I mean, if you have

```
function :: Int -> Int
function = (+12)
```

Don't call `C-c C-t` when cursor is on first-line `function`. 

Do you see any errors related to `ghc-mod` in `*Messages*` buffer?

**Comment by meditans** [comment] 2015-10-05 16:15
Strange things did happen, I got some errors for a while, now I get, when I press `C-c C-t`:

    haskell-mode-enable-process-minor-mode: Run `C-h f
    haskell-mode` for instruction how to setup a Haskell
    interaction mode.

**Comment by d12frosted** [comment] 2015-10-05 16:22
Aha! Well, that's really strange. Because if you don't enable `haskell-interactive-mode`, `C-c C-t` should work with just `ghc-mod`. 

In short, interactive mode allows you to use REPL and communicate with `ghci` instance. When you enable it, `C-c C-t` doesn't use `ghc-mod` anymore, and requires active REPL session. While it useful, let's make `C-c C-t` working with `ghc-mod`.

Does completion working for you?

Also you could try following thing.

1. Call `$ stack clean` in project root.
2. Open emacs and open any `hs` file of the project.
3. You should see how new buffer is opened with some info about setting up project.

**Comment by meditans** [comment] 2015-10-05 16:34
I didn't understand what I should try. A `stack clean` does nothing here. Did you mean to delete the `stack.yaml` file? Unfortunately I have to go now, but I'll bug you again tomorrow ;)

By the way, what's the role of the file `.dir-locals.el` in [this answer](https://www.reddit.com/r/haskell/comments/3kr6m3/update_i_got_spacemacs_working_using_stack_with/cuzzbz5)? Are those variables necessary in our approach?

**Comment by d12frosted** [comment] 2015-10-06 07:02
Hey, sorry for the late response.

No, I meant to call `$ stack clean` from the projects root. It will remove all tmp data and when you open any haskell source file in emacs (with `ghc-mod` configured) it will try to build package, and this usually brings up `ghc-mod` build buffer (I am not sure how is it called). So if you see that buffer - this is a good sign.

But again, what about completion do you get it? 

Also, could you please give a link to your `.spacemacs` file? I would like to see how you enable `haskell` layer.

**Comment by d12frosted** [comment] 2015-10-06 07:03
P. S. I removed my custom `haskell` layer, instead I am using [default](https://github.com/d12frosted/environment/blob/master/emacs/spacemacs#L48) with [shm](https://github.com/d12frosted/environment/blob/master/emacs/d12frosted/packages.el#L411).

**Comment by meditans** [comment] 2015-10-06 13:22
Hi, to reduce the space of possible problems, I begun with a new `.spacemacs`, and copied the haskell configuration (the layer invocation and every line which contains haskell) from your last `.spacemacs` file.

When I open a project, after a `stack clean`, I get, in addition to the file buffer, a buffer named `*GHC error*` with [this content](http://lpaste.net/142407). Do you happen to know how I could resolve this?

**Comment by d12frosted** [comment] 2015-10-06 13:24
```
Warning: The package list for 'hackage.haskell.org' is 24.6 days old.
Run 'cabal update' to get the latest list of available packages.
```

Looks like it doesn't use stack. Do you have `dist` directory in your project root?

**Comment by meditans** [comment] 2015-10-06 13:32
Ok, my bad, i previously renamed the `stack.yaml` and so a `dist` folder got created. However, I now removed the `dist` folder, renamed `stack.yaml`, and did a `stack clean`, just to be sure.

The error I get, however, [is very similar](http://lpaste.net/142408)

**Comment by d12frosted** [comment] 2015-10-06 13:34
Could you please share the output of following actions, please?

```
$ stack build
```

This one should end up without any problems. Then try following command. 

```
$ ghc-mod debug
```

P. S. Both of them should be called in project root.

**Comment by meditans** [comment] 2015-10-06 13:42
The output of `stack build` seems [normal, but unusually verbose](http://lpaste.net/142409).

The output of `ghc-mod debug` echoes [the previous error](http://lpaste.net/142410)

**Comment by d12frosted** [comment] 2015-10-06 13:49
Yeah, very strange output. Honestly, I don't know what's wrong. Could you try with template project like the one that is created when you call following command?

```
$ stack new helloworld new-template
```

**Comment by meditans** [comment] 2015-10-06 14:06
The error I get, with both `ghc-mod debug` and opening the file directly, is the same using the template project.
I'm starting to think this could be tied to some specific version of something I installed.. to remove all stack related things it should suffice to delete the `~/.stack` folder, right?
I'll try building everything from scratch..

**Comment by d12frosted** [comment] 2015-10-06 14:15
Yeah, it might be some strange overlapping. Looks strange to me. But you could also ask on stack repo page about this output. Cause I am not very experienced with solving such issues.

**Comment by d12frosted** [comment] 2015-10-06 14:37
So how is it going?

**Comment by meditans** [comment] 2015-10-06 14:40
I tried to install ghc-mod with a modified `stack.yaml`, and it didn't go well xD. Now I'm doing it with the one you linked, I'll keep you posted ;)

**Comment by meditans** [comment] 2015-10-06 15:27
No, sorry, everything I try to do leads eventually to the error I posted before. I'll try asking on the ghc-mod issue tracker!

**Comment by d12frosted** [comment] 2015-10-06 15:32
Ah, sorry that I can't help you with it. I am not very familiar with `stack` or `ghc-mod`. 

Also you could ask on `stack` issues page as well.

**Comment by d12frosted** [comment] 2015-10-06 15:33
Oh, by the way, I am closing this issue since in my latest commit I totally removed my private haskell layer. 

But this doesn't mean that I am not interested in solution of your problem. If you don't mind - keep me up to date! Also if you have any other questions about my settings - feel free to ask by opening new issues or writing me email. :smile:

**Closed by d12frosted** 2015-10-06 15:33 UTC
Labels: enhancement

**Comment by meditans** [comment] 2015-10-06 15:41
Thanks, you have been very helpful! I'll keep you posted :)
